
name: TON Deposit Checker

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: node checkDeposits.js
        env:
          TON_API_KEY: ${{ secrets.TON_API_KEY }}
          WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
